TESTS = dffs \
	shreg \
	iob_no_flatten \
	full_adder \
	latches \
	mac_unit \
	multiplier \
	bram \
	logic

include $(shell pwd)/../../Makefile_test.common

dffs_verify = true
shreg_verify = true
iob_no_flatten_verify = true
latches_verify = true
full_adder_verify = true
mac_unit_verify = true
multiplier_verify = true
bram_verify = true
logic_verify = true
